#!/bin/bash 
# File              : getbib
# Author            : David Barcene <david.barcene@utp.ac.pa>
# Date              : 01.03.2022
# Last Modified Date: 24.04.2022
# Last Modified By  : David Barcene <david.barcene@utp.ac.pa>

# Based on nixcasts youtube video Writing academic papers on the command 
# line with pandoc, and Luke Smith script getbib, but added the rules of
# politeness from https://api.crossref.org/swagger-ui/index.html
# Change User-Agent info  with your own before using it.
# Copy this file into your ~/.local/bin/

[ -z "$1" ] && echo "Usage: getbib [pdf] or getbib [doi]" && exit

if [ -f "$1" ]; then
	doi=$(pdfinfo "$1" | grep -io "doi:.*") ||
	doi=$(pdftotext "$1" 2>/dev/null - | grep -io "doi.*" -m 1 | sed "s/^..../doi:/") ||
	exit 1
else
	doi="$1"
fi

# Check crossref.org for bibtex citation
curl -X GET \
	"https://api.crossref.org/works/$doi/transform/application/x-bibtex" \
	-H 'User-Agent: dbarcene (mailto:david.barcene@utp.ac.pa)' \
	-w "\\n"
